[package]
name = "parser_combinators"
version = "0.1.0"
authors = ["AnicetNgrt <anicet.nougaret@zohomail.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
